# This is the environment needed to build quagmire. As this will be cached, we can include any dependencies
# so they are not downloaded again - this should save a bit of time

name: conda-build
channels: 
  - conda-forge
dependencies:
  - conda-build 
  - conda-verify


