{% set name = "quagmire" %}
{% set version = "0.9.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - setuptools
    - numpy >=1.16
  host:
    - python
    - petsc4py
    - h5py
  run:
    - python
    - numpy
    - scipy
    - stripy
    - petsc4py
    - mpi4py
    - h5py
    - pint

about:
  home: "https://github.com/underworldcode/quagmire"

extra:
  recipe-maintainers:
    - lmoresi
    - brmather
    - rbeucher
